[LightDM]
run-directory=/var/run/lightdm
log-directory=/var/log/lightdm
cache-directory=/var/cache/lightdm
start-default-seat=true

[Seat:*]
xserver-command=/etc/lightdm/xkasmvnc-wrapper
xserver-share=true
greeter-session=lightdm-gtk-greeter
greeter-hide-users=false
greeter-show-manual-login=true
greeter-allow-guest=false
allow-guest=false
session-wrapper=/etc/lightdm/Xsession
user-session=xfce
autologin-user=
autologin-user-timeout=0
